export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const SET_AUTH_VERIFIER_ID = "SET_AUTH_VERIFIER_ID";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SERIES_SUCCESS = "SERIES_SUCCESS";
export const ADD_SERIES_GALLERY = 'ADD_SERIES_GALLERY';
export const REMOVE_SERIES_GALLERY = 'REMOVE_SERIES_GALLERY';
export const SET_SERIES = "SET_SERIES";

export const ADD_SEASON_EPISODE = 'ADD_SEASON_EPISODE';
export const REMOVE_SEASON_EPISODE = 'REMOVE_SEASON_EPISODE';
export const SEASON_SUCCESS = "SEASON_SUCCESS";

export const EPISODE_SUCCESS = "EPISODE_SUCCESS";

export const SET_USERS = "SET_USERS";
export const USER_SUCCESS = "USER_SUCCESS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const SET_MOVIES = "SET_MOVIES";
export const ADD_MOVIE_GALLERY = 'ADD_MOVIE_GALLERY';
export const REMOVE_MOVIE_GALLERY = 'REMOVE_MOVIE_GALLERY';
export const MOVIE_SUCCESS = "MOVIE_SUCCESS";

export const SET_CHANNELS = "SET_CHANNELS";
export const ADD_CHANNEL_GALLERY = 'ADD_CHANNEL_GALLERY';
export const REMOVE_CHANNEL_GALLERY = 'REMOVE_CHANNEL_GALLERY';
export const CHANNEL_SUCCESS = "CHANNEL_SUCCESS";